<?php

/*
 | Katalog tool: satu-satunya sumber kebenaran untuk navigasi, daftar di
 | halaman depan, dan pendaftaran route. Menambah tool baru = menambah entri
 | di sini + satu view di resources/views/tools/.
 |
 | status:
 |   ready   -> halaman sudah ada, route didaftarkan, tautan bisa diklik
 |   planned -> tampil sebagai roadmap (badge "segera"), tidak ada route
 |
 | accent dipakai untuk warna blok di UI; nilai yang valid ada di
 | resources/views/components/ui/badge.blade.php (tempat class Tailwind ditulis).
 */

return [
    'categories' => [
        'Format & Validasi' => [
            'accent' => 'wave',
            'blurb' => 'Rapikan dan validasi data terstruktur tanpa mengirim isinya ke server.',
        ],
        'Encode & Decode' => [
            'accent' => 'mint',
            'blurb' => 'Konversi representasi data bolak-balik, semuanya di sisi browser.',
        ],
        'Hash & Generator' => [
            'accent' => 'sun',
            'blurb' => 'Buat hash, UUID, dan ekspresi terjadwal langsung dari browser.',
        ],
        'Konversi Data' => [
            'accent' => 'punch',
            'blurb' => 'Ubah satu format ke format lain, termasuk pasangan yang jarang disediakan.',
        ],
        'Teks & Utilitas' => [
            'accent' => 'acid',
            'blurb' => 'Alat bantu untuk teks, pola pencarian, dan pemeriksaan harian.',
        ],
        'Data Referensi' => [
            'accent' => 'paper-dim',
            'blurb' => 'Daftar data siap pakai untuk kebutuhan formulir dan pengembangan aplikasi lokal.',
        ],
    ],

    'tools' => [
        'json-formatter' => [
            'name' => 'JSON Formatter & Validator',
            'short_name' => 'JSON Formatter',
            'tagline' => 'Rapikan, validasi, dan perkecil JSON langsung di browser.',
            'description' => 'Format dan validasi JSON online. Tempel JSON, dapatkan hasil rapi dengan indentasi 2 spasi, 4 spasi, atau tab, plus pesan error yang menunjukkan baris dan kolom. Diproses di browser, data tidak dikirim ke server.',
            'category' => 'Format & Validasi',
            'keywords' => 'json, json formatter, json validator, beautify, pretty print, minify, format json',
            'status' => 'ready',
            'view' => 'tools.json-formatter',
            'script' => 'resources/js/tools/json-formatter.js',
            'how_to' => [
                'Tempel JSON ke panel <strong>Input</strong>, atau klik <strong>Contoh</strong> untuk mencoba dengan data uji.',
                'Klik <strong>Format</strong> untuk merapikan, <strong>Minify</strong> untuk memadatkan, atau <strong>Validasi</strong> bila hanya ingin memeriksa.',
                'Klik <strong>Urutkan kunci</strong> untuk menyusun kunci objek dari A ke Z — berguna saat membandingkan dua respons API.',
                'Salin hasilnya lewat <strong>Salin hasil</strong>, atau unduh sebagai berkas <code>.json</code>.',
            ],
            'faq' => [
                ['q' => 'Apakah data JSON saya dikirim ke server?', 'a' => 'Tidak. Seluruh proses memakai JSON.parse dan JSON.stringify di browser Anda.'],
                ['q' => 'Pesan error menunjuk baris dan kolom — dari mana?', 'a' => 'Dari posisi karakter yang gagal dibaca parser. Pesan seperti "baris 3, kolom 5" bisa langsung Anda cari di panel input.'],
                ['q' => 'Penyebab error JSON yang paling sering apa?', 'a' => 'Koma berlebih di akhir objek atau array, tanda kutip tunggal, komentar, dan kunci tanpa tanda kutip — ketiganya tidak diizinkan dalam JSON yang sah.'],
                ['q' => 'Berapa besar berkas JSON yang bisa diproses?', 'a' => 'Beberapa megabyte masih nyaman. Karena diproses di sisi klien, kecepatannya bergantung pada perangkat Anda.'],
            ],
        ],
        'xml-formatter' => [
            'name' => 'XML Formatter & Validator',
            'short_name' => 'XML Formatter',
            'tagline' => 'Rapikan XML dan temukan tag yang tidak seimbang.',
            'description' => 'Format dan validasi XML online dengan indentasi yang bisa diatur dan penunjuk baris error.',
            'category' => 'Format & Validasi',
            'keywords' => 'xml, xml formatter, xml validator, beautify xml',
            'status' => 'ready',
            'view' => 'tools.xml-formatter',
            'script' => 'resources/js/tools/xml-formatter.js',
            'how_to' => [
                'Tempel XML ke panel <strong>Input</strong>, atau klik <strong>Contoh</strong> untuk data uji.',
                'Klik <strong>Format</strong> untuk merapikan, atau <strong>Minify</strong> untuk menghapus spasi antar tag.',
                'Klik <strong>Validasi</strong> bila hanya ingin memeriksa keseimbangan tag.',
                'Atur kedalaman indentasi (2 spasi, 4 spasi, atau tab) sesuai gaya proyek Anda.',
            ],
            'faq' => [
                ['q' => 'Apakah komentar, CDATA, dan namespace tetap utuh?', 'a' => 'Ya. Dokumen dibaca ulang sebagai pohon XML oleh parser bawaan browser, jadi namespace, komentar, CDATA, dan atribut dipertahankan — hanya spasi antar elemen yang dirapikan.'],
                ['q' => 'Kenapa referensi seperti &#65; berubah menjadi A?', 'a' => 'Karena hasil ditulis ulang dari pohon XML, referensi karakter dikembalikan ke bentuk karakternya. Isi dokumen tetap sama.'],
                ['q' => 'Berapa besar XML yang bisa diproses?', 'a' => 'Beberapa megabyte masih nyaman. Karena diproses di browser, kecepatannya bergantung pada perangkat Anda.'],
                ['q' => 'Apakah XML saya dikirim ke server?', 'a' => 'Tidak. Tidak ada request yang membawa isi input Anda.'],
            ],
        ],
        'html-formatter' => [
            'name' => 'HTML Formatter',
            'short_name' => 'HTML Formatter',
            'tagline' => 'Rapikan markup HTML yang berantakan.',
            'description' => 'Format HTML online dengan indentasi konsisten, plus mode minify untuk produksi.',
            'category' => 'Format & Validasi',
            'keywords' => 'html, html formatter, html beautifier, minify html',
            'status' => 'planned',
        ],
        'sql-formatter' => [
            'name' => 'SQL Formatter',
            'short_name' => 'SQL Formatter',
            'tagline' => 'Bikin query panjang terbaca lagi.',
            'description' => 'Format query SQL dengan pilihan dialek (MySQL, PostgreSQL, SQL Server) dan indentasi yang bisa diatur.',
            'category' => 'Format & Validasi',
            'keywords' => 'sql, sql formatter, query formatter, beautify sql',
            'status' => 'planned',
        ],
        'css-formatter' => [
            'name' => 'CSS Formatter & Minifier',
            'short_name' => 'CSS Formatter',
            'tagline' => 'Rapikan atau padatkan CSS.',
            'description' => 'Format CSS agar mudah dibaca, atau minify untuk mengecilkan ukuran berkas.',
            'category' => 'Format & Validasi',
            'keywords' => 'css, css formatter, css minifier, beautify css',
            'status' => 'planned',
        ],
        'javascript-formatter' => [
            'name' => 'JavaScript Formatter & Minifier',
            'short_name' => 'JS Formatter',
            'tagline' => 'Rapikan JavaScript tanpa mengubah perilakunya.',
            'description' => 'Format dan minify JavaScript langsung di browser.',
            'category' => 'Format & Validasi',
            'keywords' => 'javascript, js formatter, js beautifier, minify javascript',
            'status' => 'planned',
        ],

        'base64' => [
            'name' => 'Base64 Encode / Decode',
            'short_name' => 'Base64',
            'tagline' => 'Ubah teks menjadi Base64 dan sebaliknya.',
            'description' => 'Encode dan decode Base64 online, termasuk dukungan UTF-8 dan mode URL-safe.',
            'category' => 'Encode & Decode',
            'keywords' => 'base64, base64 encode, base64 decode, url safe base64',
            'status' => 'ready',
            'view' => 'tools.base64',
            'script' => 'resources/js/tools/base64.js',
            'how_to' => [
                'Tempel teks biasa untuk <strong>Encode</strong>, atau Base64 untuk <strong>Decode</strong>.',
                'Tombol <strong>Otomatis</strong> menebak mode dari isi input — praktis kalau Anda menemukan string Base64 tanpa keterangan.',
                'Centang <strong>Base64 URL-safe</strong> bila hasilnya akan dipakai di URL, nama berkas, atau JWT.',
                'Salin atau unduh hasilnya lewat tombol di bilah atas.',
            ],
            'faq' => [
                ['q' => 'Kenapa hasil encode jadi sekitar sepertiga lebih panjang?', 'a' => 'Base64 mengubah 3 byte menjadi 4 karakter. Teks non-ASCII juga memakai lebih dari satu byte UTF-8, jadi hasilnya bisa lebih panjang lagi.'],
                ['q' => 'Decode gagal dengan pesan "bukan teks UTF-8" — kenapa?', 'a' => 'Isi Base64 tersebut kemungkinan data biner seperti gambar atau arsip. Centang "izinkan data biner" untuk melihat hasilnya sebagai teks dengan karakter pengganti.'],
                ['q' => 'Apa itu Base64 URL-safe?', 'a' => 'Varian yang mengganti + menjadi -, / menjadi _, dan menghapus padding =, supaya aman dipakai di dalam URL atau nama berkas.'],
                ['q' => 'Apakah teks saya dikirim ke server?', 'a' => 'Tidak. Encode dan decode memakai fungsi bawaan browser (btoa/atob), jadi tidak ada data yang keluar dari perangkat Anda.'],
            ],
        ],
        'url-encoder' => [
            'name' => 'URL Encode / Decode',
            'short_name' => 'URL Encoder',
            'tagline' => 'Persen-encode URL dan query string.',
            'description' => 'Encode dan decode komponen URL, termasuk mode encodeURIComponent dan encodeURI.',
            'category' => 'Encode & Decode',
            'keywords' => 'url encode, url decode, percent encoding, query string',
            'status' => 'ready',
            'view' => 'tools.url-encoder',
            'script' => 'resources/js/tools/url-encoder.js',
            'how_to' => [
                'Tempel URL atau nilai parameter ke panel <strong>Input</strong>.',
                'Pilih mode: <strong>Komponen</strong> (encodeURIComponent) untuk satu nilai, atau <strong>URL utuh</strong> (encodeURI) untuk alamat lengkap.',
                'Klik <strong>Encode</strong> atau <strong>Decode</strong>.',
                'Tombol <strong>Baca parameter</strong> memecah query string menjadi daftar <code>kunci = nilai</code>.',
            ],
            'faq' => [
                ['q' => 'Apa bedanya mode komponen dan URL utuh?', 'a' => 'Mode komponen meng-encode semua karakter khusus termasuk / ? & =, jadi cocok untuk satu nilai. Mode URL utuh membiarkan pemisah struktur URL apa adanya.'],
                ['q' => 'Kenapa spasi menjadi %20, bukan +?', 'a' => '%20 adalah bentuk resmi dalam standar URL. Tanda + hanya konvensi pengiriman form HTML, jadi kami tidak memakainya.'],
                ['q' => 'Decode gagal dengan pesan "escape tidak sah"?', 'a' => 'Artinya ada tanda % yang tidak diikuti dua digit heksadesimal, misalnya "%ZZ" atau "%" di akhir teks.'],
                ['q' => 'Apakah URL saya dicatat?', 'a' => 'Tidak. Seluruh proses berjalan di browser; tidak ada permintaan jaringan yang membawa isi input Anda.'],
            ],
        ],
        'html-entities' => [
            'name' => 'HTML Entity Encode / Decode',
            'short_name' => 'HTML Entities',
            'tagline' => 'Ubah karakter khusus jadi entitas HTML.',
            'description' => 'Encode dan decode entitas HTML untuk mencegah markup rusak atau celah XSS.',
            'category' => 'Encode & Decode',
            'keywords' => 'html entity, html encode, html decode, escape html',
            'status' => 'ready',
            'view' => 'tools.html-entities',
            'script' => 'resources/js/tools/html-entities.js',
            'how_to' => [
                'Tempel teks atau potongan markup ke panel <strong>Input</strong>.',
                'Klik <strong>Encode</strong>. Pilih entitas <strong>bernama</strong> (&amp;amp;) atau <strong>numerik</strong> (&amp;#38;).',
                'Centang <strong>ASCII saja</strong> bila hasilnya harus aman di encoding lama.',
                'Klik <strong>Decode</strong> untuk mengembalikan entitas menjadi karakter aslinya.',
            ],
            'faq' => [
                ['q' => 'Kapan perlu meng-encode entitas HTML?', 'a' => 'Saat menampilkan potongan kode di halaman web agar tidak dirender sebagai markup, dan saat menulis nilai pengguna ke HTML untuk mencegah XSS.'],
                ['q' => 'Entitas apa saja yang bisa di-decode?', 'a' => 'Sekitar 45 entitas bernama yang umum dipakai, ditambah semua referensi numerik desimal (&#38;) maupun heksadesimal (&#x26;).'],
                ['q' => 'Apakah markup yang ditempel bisa dieksekusi?', 'a' => 'Tidak. Decode memakai peta entitas, bukan parser DOM, jadi tidak ada script atau tag yang dijalankan.'],
                ['q' => 'Teks saya dikirim ke server?', 'a' => 'Tidak. Prosesnya murni di browser tanpa permintaan jaringan.'],
            ],
        ],
        'jwt-decoder' => [
            'name' => 'JWT Decoder',
            'short_name' => 'JWT Decoder',
            'tagline' => 'Baca header dan payload JWT.',
            'description' => 'Decode JWT dan lihat header, payload, serta waktu kedaluwarsa tanpa mengirim token ke server. Jangan pernah menempelkan token produksi ke tool yang menyimpan datanya.',
            'category' => 'Encode & Decode',
            'keywords' => 'jwt, jwt decoder, json web token, decode jwt',
            'status' => 'planned',
        ],
        'string-escape' => [
            'name' => 'String Escape / Unescape',
            'short_name' => 'String Escape',
            'tagline' => 'Escape string untuk JSON, JS, dan SQL.',
            'description' => 'Ubah string menjadi bentuk yang aman dipakai di dalam kode JSON, JavaScript, Java, atau SQL.',
            'category' => 'Encode & Decode',
            'keywords' => 'escape string, unescape, escape json, escape sql',
            'status' => 'planned',
        ],

        'hash-generator' => [
            'name' => 'Hash Generator (MD5, SHA-1, SHA-256, SHA-512)',
            'short_name' => 'Hash Generator',
            'tagline' => 'Hitung hash teks atau berkas.',
            'description' => 'Buat hash MD5, SHA-1, SHA-256, dan SHA-512 dari teks maupun berkas, dihitung di browser memakai Web Crypto API.',
            'category' => 'Hash & Generator',
            'keywords' => 'hash generator, md5, sha1, sha256, checksum',
            'status' => 'ready',
            'view' => 'tools.hash-generator',
            'script' => 'resources/js/tools/hash-generator.js',
            'how_to' => [
                'Centang algoritma yang dibutuhkan — boleh lebih dari satu sekaligus.',
                'Tempel teks ke <strong>Input</strong>, atau pilih berkas lewat <strong>Pilih berkas</strong>.',
                'Klik <strong>Hitung hash</strong>; hasilnya tampil sejajar per algoritma.',
                'Salin hasilnya untuk dibandingkan dengan checksum resmi dari situs penyedia unduhan.',
            ],
            'faq' => [
                ['q' => 'Apakah MD5 masih boleh dipakai?', 'a' => 'Untuk keamanan, tidak — MD5 dan SHA-1 sudah dianggap patah. Keduanya masih berguna sebagai checksum berkas atau untuk mencocokkan sistem lama. Untuk password, gunakan bcrypt atau Argon2, bukan hash cepat seperti di halaman ini.'],
                ['q' => 'Kenapa SHA gagal dihitung di lingkungan tertentu?', 'a' => 'SHA-1/256/384/512 memakai Web Crypto API yang hanya aktif di secure context (HTTPS atau localhost). MD5 tetap bekerja karena implementasinya murni JavaScript.'],
                ['q' => 'Apakah berkas yang saya pilih diunggah?', 'a' => 'Tidak. Berkas dibaca di memori browser dan hanya dipakai untuk menghitung hash di perangkat Anda.'],
                ['q' => 'Bisakah menghitung banyak berkas sekaligus?', 'a' => 'Belum. Untuk sekarang satu teks atau satu berkas per perhitungan.'],
            ],
        ],
        'hmac-generator' => [
            'name' => 'HMAC Generator',
            'short_name' => 'HMAC Generator',
            'tagline' => 'Hitung tanda tangan HMAC dengan kunci rahasia.',
            'description' => 'Buat HMAC berbasis SHA-256 dan SHA-512 dari pesan dan kunci rahasia, diproses sepenuhnya di browser.',
            'category' => 'Hash & Generator',
            'keywords' => 'hmac, hmac generator, signature, webhook signature',
            'status' => 'planned',
        ],
        'uuid-generator' => [
            'name' => 'UUID / GUID Generator',
            'short_name' => 'UUID Generator',
            'tagline' => 'Buat UUID v4 dan v7, satu atau sekaligus banyak.',
            'description' => 'Generator UUID v4 dan v7 (time-ordered) dengan opsi buat banyak sekaligus dan salin cepat.',
            'category' => 'Hash & Generator',
            'keywords' => 'uuid, uuid generator, guid, uuid v4, uuid v7',
            'status' => 'ready',
            'view' => 'tools.uuid-generator',
            'script' => 'resources/js/tools/uuid-generator.js',
            'how_to' => [
                'Pilih versi: <strong>v4</strong> (acak) atau <strong>v7</strong> (terurut menurut waktu).',
                'Tentukan jumlah UUID yang ingin dibuat (maksimal 1000 sekaligus).',
                'Atur format: huruf besar, tanpa tanda hubung, atau dibungkus kurung kurawal.',
                'Salin seluruh hasil atau unduh sebagai berkas teks.',
            ],
            'faq' => [
                ['q' => 'Kapan sebaiknya memakai UUID v7?', 'a' => 'Saat UUID dipakai sebagai primary key. v7 memuat timestamp di bagian depan sehingga nilainya terurut menurut waktu — indeks database jadi lebih efisien dibanding v4 yang acak.'],
                ['q' => 'Apakah UUID yang dibuat di sini aman?', 'a' => 'Ya. Nilai acaknya diambil dari crypto.getRandomValues, sumber acak kriptografis bawaan browser, bukan Math.random.'],
                ['q' => 'Apakah UUID saya dicatat di server?', 'a' => 'Tidak. Semuanya dibuat di browser dan tidak dikirim ke mana pun.'],
                ['q' => 'Bisakah membuat UUID tanpa tanda hubung?', 'a' => 'Bisa. Centang opsi "tanpa tanda hubung" — berguna untuk nama berkas atau kolom database bertipe string 32 karakter.'],
            ],
        ],
        'cron-generator' => [
            'name' => 'Cron Expression Generator',
            'short_name' => 'Cron Generator',
            'tagline' => 'Susun ekspresi cron dan baca artinya.',
            'description' => 'Buat dan uji ekspresi cron, lengkap dengan penjelasan waktu jalan dalam bahasa manusia.',
            'category' => 'Hash & Generator',
            'keywords' => 'cron, cron expression, cron generator, crontab, quartz',
            'status' => 'planned',
        ],

        'csv-to-json' => [
            'name' => 'CSV ke JSON',
            'short_name' => 'CSV → JSON',
            'tagline' => 'Ubah CSV menjadi array JSON.',
            'description' => 'Konversi CSV ke JSON dengan pilihan pemisah kolom, baris judul, dan tipe data.',
            'category' => 'Konversi Data',
            'keywords' => 'csv to json, konversi csv, csv converter',
            'status' => 'planned',
        ],
        'json-to-yaml' => [
            'name' => 'JSON ke YAML',
            'short_name' => 'JSON → YAML',
            'tagline' => 'Ubah JSON menjadi YAML yang rapi.',
            'description' => 'Konversi JSON ke YAML dan sebaliknya tanpa kehilangan struktur.',
            'category' => 'Konversi Data',
            'keywords' => 'json to yaml, yaml to json, konversi yaml',
            'status' => 'planned',
        ],
        'xml-to-json' => [
            'name' => 'XML ke JSON',
            'short_name' => 'XML → JSON',
            'tagline' => 'Ubah dokumen XML menjadi JSON.',
            'description' => 'Konversi XML ke JSON dengan penanganan atribut dan namespace yang bisa diatur.',
            'category' => 'Konversi Data',
            'keywords' => 'xml to json, konversi xml, xml converter',
            'status' => 'planned',
        ],
        'timestamp-converter' => [
            'name' => 'Unix Timestamp Converter',
            'short_name' => 'Timestamp Converter',
            'tagline' => 'Ubah epoch ke tanggal dan sebaliknya.',
            'description' => 'Konversi Unix timestamp ke tanggal ISO dan waktu lokal Indonesia, serta sebaliknya.',
            'category' => 'Konversi Data',
            'keywords' => 'unix timestamp, epoch converter, tanggal iso, timestamp online',
            'status' => 'planned',
        ],

        'word-counter' => [
            'name' => 'Penghitung Kata & Pengubah Kapitalisasi',
            'short_name' => 'Word Counter',
            'tagline' => 'Hitung kata, karakter, dan ubah besar-kecil huruf.',
            'description' => 'Hitung jumlah kata, karakter, dan paragraf, sekaligus ubah teks ke huruf besar, kecil, judul, atau slug.',
            'category' => 'Teks & Utilitas',
            'keywords' => 'word counter, karakter, case converter, hitung kata',
            'status' => 'planned',
        ],
        'regex-tester' => [
            'name' => 'Regex Tester',
            'short_name' => 'Regex Tester',
            'tagline' => 'Uji pola regex beserta grup tangkapannya.',
            'description' => 'Uji ekspresi reguler terhadap teks contoh, lihat semua kecocokan dan grup tangkapan secara langsung.',
            'category' => 'Teks & Utilitas',
            'keywords' => 'regex, regex tester, regular expression, uji regex',
            'status' => 'planned',
        ],
        'xpath-tester' => [
            'name' => 'XPath Tester',
            'short_name' => 'XPath Tester',
            'tagline' => 'Cari node XML dengan ekspresi XPath.',
            'description' => 'Uji ekspresi XPath terhadap dokumen XML dan lihat node yang cocok.',
            'category' => 'Teks & Utilitas',
            'keywords' => 'xpath, xpath tester, xml query',
            'status' => 'planned',
        ],
        'lorem-ipsum' => [
            'name' => 'Lorem Ipsum Generator',
            'short_name' => 'Lorem Ipsum',
            'tagline' => 'Teks contoh untuk tata letak.',
            'description' => 'Buat teks contoh dalam satuan kata, kalimat, atau paragraf.',
            'category' => 'Teks & Utilitas',
            'keywords' => 'lorem ipsum, teks contoh, dummy text',
            'status' => 'planned',
        ],

        'provinsi-indonesia' => [
            'name' => 'Daftar Provinsi & Kota di Indonesia',
            'short_name' => 'Provinsi & Kota',
            'tagline' => 'Daftar provinsi dan kabupaten/kota siap salin.',
            'description' => 'Daftar provinsi, kabupaten/kota, dan kecamatan di Indonesia dalam format tabel, JSON, CSV, dan tag select HTML.',
            'category' => 'Data Referensi',
            'keywords' => 'daftar provinsi indonesia, daftar kota, select option indonesia',
            'status' => 'planned',
        ],
        'kode-pos-indonesia' => [
            'name' => 'Daftar Kode Pos Indonesia',
            'short_name' => 'Kode Pos',
            'tagline' => 'Cari kode pos berdasarkan wilayah.',
            'description' => 'Cari kode pos Indonesia berdasarkan kelurahan, kecamatan, atau kota.',
            'category' => 'Data Referensi',
            'keywords' => 'kode pos, cari kode pos, kodepos indonesia',
            'status' => 'planned',
        ],
        'mime-types' => [
            'name' => 'Daftar MIME Type',
            'short_name' => 'MIME Types',
            'tagline' => 'Tabel MIME type untuk konfigurasi berkas.',
            'description' => 'Daftar lengkap MIME type beserta ekstensi berkas, siap dipakai untuk header atau konfigurasi server.',
            'category' => 'Data Referensi',
            'keywords' => 'mime type, content type, daftar mime',
            'status' => 'planned',
        ],
    ],
];
